### PR TITLE
Use the default Kryo serializer for Enumeration-s

### PR DESCRIPTION
**Pull request by luben**
Addresses #75

The current specialized serializer has concurrency bug
in maintaining the caches and is not faster than the
default Kryo serializer for Enumeration-s. Here are
some benchmarks:

The specialized Enumeration serializer:

> testOnly com.romix.akka.serialization.kryo.EnumTest
Enum Serialize:   :     2178    ms      =       4591    ops/s
Enum Serialize:   :     1526    ms      =       6553    ops/s
Enum Serialize:   :     1549    ms      =       6455    ops/s
Enum Deserialize: :     1141    ms      =       8764    ops/s
Enum Deserialize: :     1028    ms      =       9727    ops/s
Enum Deserialize: :     1040    ms      =       9615    ops/s
[info] EnumTest:
[info] Enumeration serialization
[info] - should be fast
[info] - should be threadsafe *** FAILED ***

The default Kryo serializer:

[success] Total time: 10 s, completed 19-Feb-2016 13:35:19
> testOnly com.romix.akka.serialization.kryo.EnumTest
Enum Serialize:   :     1445    ms      =       6920    ops/s
Enum Serialize:   :     1331    ms      =       7513    ops/s
Enum Serialize:   :     1332    ms      =       7507    ops/s
Enum Deserialize: :     1210    ms      =       8264    ops/s
Enum Deserialize: :     1072    ms      =       9328    ops/s
Enum Deserialize: :     1019    ms      =       9813    ops/s
[info] EnumTest:
[info] Enumeration serialization
[info] - should be fast
[info] - should be threadsafe

### CODE REVIEW

**Comment by romix** [comment]
IIRC, the reason why I introduced the dedicated enums serializer for Scala was not the performance, but the fact that the standard enum serializer from Kryo could not handle all the corner cases that happen with Scala enums. There were probably some issues about this. Could you check for the related bug reports in the closed issues and check if Kryo can handle all such cases?

**Comment by luben** [comment]
Yes, sure. I will check and also restore some of the test cases

**Comment by stefan-mees** [comment]
I would suggest to check Twitter implementation, i believe creating new instances of Objects (Enums) should be avoided in all cases.

https://github.com/twitter/chill/blob/0bc489d9a42774324259e8a47565dae880072b93/chill-scala/src/main/scala/com/twitter/chill/EnumerationSerializer.scala

**Comment by luben** [comment]
Yes, you are both right. Let'd discard this PR and I will look to improve the current Enumeration serializer, possibly stealing from the Chill implementation.

**Pull request closed without merging**
