### PR TITLE
Added Unit/BoxedUnit serializers and tests

### PR DESCRIPTION
**Pull request by luben**
It addresses #89

### CODE REVIEW

**Comment by luben** [comment]
It should be ready for 0.4.2 release. Do you want me to add also  the README/version changes for the release?

**Comment by romix** [comment]
@luben Thanks, looks good!

And yes, if you could prepare the README/version changes for the release, it would be nice.

**Comment by luben** [comment]
Updated the version. Please note that the README was also updated with information about the forthcoming 0.5.0 release based on Kryo-4.0

**Comment by romix** [comment]
Thanks! Could you provide the release related changes in a separate PR? Let's not mix it with the code changes. I'm also not sure about the `version.sbt` change. IIRC, the release plugin updates it automatically.

**Comment by luben** [comment]
Done. Moved it to a separate PR for 0.4.2 release. I have also reverted the version.sbt as you suggested. I am preparing the changes and PR for 0.5.0 based on Kryo-4.0

**Pull request merged**
