### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by luben**
Update dependecy and prepare for v0.5.0
    
    We have to bump the version as Kryo-4.0 is not
    compatible with Kryo-3.0

### CODE REVIEW

**Comment by romix** [comment]
This commit also seems to contain Unit and BoxedUnit changes, which were committed in a separate PR.

**Comment by luben** [comment]
yes,it will not duplicate them when you merge it - it shows the difference between your tree and my tree that is 4 commits ahead.

**Comment by luben** [comment]
re-submitted the 0.4.2 release PR. I will re-submit this one ofter it is committed in order not to include the old commit messages.

**Comment by luben** [comment]
One other question is: should we provide config switch for setOptimizedGenerics(true) in 0.5.0 ?

My take is that this is not the only breaking change with Kryo-4.0 and it will provide false sense of compatibility with Kryo-3.0. Better break clean. If somebody needs it so badly it can still be set from the custom initializer class.

**Pull request merged**
