### PR TITLE
Update for Akka 2.4.0 #56

### PR DESCRIPTION
**Pull request by tuxdna**
Fix issue: 

https://github.com/romix/akka-kryo-serialization/issues/56

### CODE REVIEW

**Comment by tuxdna** [comment]
Please review and merge this PR.

**Comment by guidomedina** [comment]
Actually the `crossScalaVersions` should be pointing to 2.10.6 instead of 2.10.4 but either way it would be not worth doing that because Akka 2.4 dropped support of Scala 2.10 and instead is supporting only 2.11 and 2.12, but 2.12 is still in milestone which makes Akka dependency variable to the Scala 2.12-MX until it is released so I would release only support for 2.11 for now.

And later when Scala 2.12 stable is out then re-add it.

**Comment by luben** [comment]
There are a bunch of problems and possibilities here:

1. Akka-2.4 is API and binary compatible with Akka-2.3 and just overriding akka version will work (with a sbt warning)

2. I agree we have to drop Scala-2.10 if we start depending on Akka-2.4. In my view this requires version bump.

3. I like the proposed changes to replace system.actorFor that was deprecated long time ago.

tuxdna@ do you currently have problems using the extension with Akka version override?

My suggestion is to release new version with support for Akka-2.4 + Scala-2.11 + Scala-2.12 but I suggest waiting for Scala-2.12-RC to become available - the milestone releases don't guarantee binary compatibility.

**Comment by guidomedina** [comment]
Exactly, a version bump and suspend support of 2.12 due to binary compatibility until RC and up are available, also Akka 2.4 dependency name changes from one Scala 2.12 milestone to another so it will be only a hassle to try to support it now.

**Comment by tuxdna** [comment]
@luben Yes, only support for Scala 2.11would be good. We can use bumped version of akka-kryo-serialization, with no problem.

**Comment by romix** [comment]
@luben @tuxdna Guys, I'm currently pretty busy with other things. But if you prepare and test the PRs, I'm fine with merging them.

@luben I appreciate your support! If these changes will get a green light from you, I'd merge and roll out a new release.

**Comment by tuxdna** [comment]
@romix: Thats a great news. I am looking forward for a release :-)

**Comment by luben** [comment]
@tuxdna: I will base the PR on your work, can you send me the same PR to luben/akka-kryo-serialization.

@guidomedina: the plan for Scala-2.12 is to not include Akka and Actors packages in the distribution, so one less problem but we have to wait for binary compatibility stabilization anyway.

**Comment by tuxdna** [comment]
@luben  I just created this PR in your fork: https://github.com/luben/akka-kryo-serialization/pull/1

**Comment by luben** [comment]
OK, thanks. I will work on it this week, I have a project running on Akka-2.4 where I want to test it.

**Comment by tuxdna** [comment]
@luben Great! Sounds like it would be fun already :-)

**Comment by guidomedina** [comment]
I have been using Kryo with Akka 2.4.0 for some time now using the following:

Relevant versions in general:
```
      <akka.version>2.4.0</akka.version>
      <scala.version>2.11</scala.version>
      <scala.lib.version>2.11.7</scala.lib.version>
      <scala.plugin.version>3.2.2</scala.plugin.version>
      <akka.kryo.version>0.3.3</akka.kryo.version>
      <kryo.version>3.0.3</kryo.version>
      <reflectasm.version>1.11.0</reflectasm.version>
      <asm.version>5.0.4</asm.version>
```

Dependency declaration:
```
      <dependency>
         <groupId>com.github.romix.akka</groupId>
         <artifactId>akka-kryo-serialization_2.11</artifactId>
         <version>${akka.kryo.version}</version>
         <exclusions>
            <exclusion>
               <groupId>com.typesafe.akka</groupId>
               <artifactId>akka-kernel_2.11</artifactId>
            </exclusion>
         </exclusions>
      </dependency>
```

**Comment by luben** [comment]
@romix @tuxdna @guidomedina @JosephKiranBabu , please take a look at #58 - it is based on this one. I suppose we can close this PR

**Comment by JosephKiranBabu** [comment]
Great work @luben ! 

Waiting for the artifacts to be published to maven.

**Comment by guidomedina** [comment]
Very nice, I see you also took care of Kryo dependency, great work @luben

**Pull request merged**
