### PR TITLE
Test for #67

### PR DESCRIPTION
**Pull request by briantopping**
See the thread on EsotericSoftware/kryo#379. I'm not sure exactly where the problem is here, but `ScalaCollectionsSerializer` is in the call chain, so it's probably better to start here.

Thanks to Martin Grotzke for the help with this!

### CODE REVIEW

**Comment by luben** [comment]
Hi Brian,

Your test is not fully correct. It fails because you try to assert that

Class[Success[X ]] equals Class[X]

Your logic is not correct also. ByteString is IndexedSeq[Byte] that itself is Traversable, the kryo serializer picks the generic collections serializer I guess: "ScalaCollectionSerializer" for serializing. I still don't know why it serializes as a Vector[Byte] though

**Comment by briantopping** [comment]
Thanks @luben, I just corrected the first issue while you were writing that. Apologies it wasn't correct to start with.

I don't understand the logic error you believe is there though. The return from deserialization should be `equals` as well as the same class, no?

**Comment by luben** [comment]
OK,
went with some debugging. it's not fault of the serialization library. Here it what happens:

It picks the generic ScalaCollectionSerializer. The reader creates an empty instance of ByteString$ByteString1C and asks it which builder to use: inst.genericBuilder returns VectorBuilder (why I haven't looked in detail). So it uses it and the final result is Vector.

**Comment by briantopping** [comment]
Thanks, so are you saying that this is a problem with Kryo after all? 

@maguro is going to say "generate a test case that doesn't have Akka in it". I'm kind of fscked right now.

**Comment by luben** [comment]
No the problem is with the ByteString. You can verify it with:
```scala
  ByteString("foo").genericBuilder.getClass
  ByteString("foo").compact.genericBuilder.getClass
```

**Comment by briantopping** [comment]
Indeed. I will track this down with Akka team and close this as soon as I get a resolution. Thanks a lot!

**Comment by luben** [comment]
I suppose it is just implementing the method in ByteString trait, it should be something like:
```scala
def genericBuilder = ByteString.newBuilder
```

**Comment by briantopping** [comment]
Thanks! I think this was just recently fixed in akka/akka#19085, which is timely since the 2.4 build is only just usable starting today with Akka-HTTP. I was setting up a test case in Akka and it was working fine, I am like "huh??!?". Will update and close as soon as I can verify that everything is working.

**Comment by luben** [comment]
I am not sure it adds the genericBuilder method, it looks more like fixing the newBuilder to work from Java. I may be wrong.

**Comment by briantopping** [comment]
Akka is running pretty well from `master` now, but the problem still exists in the REPL and in my app. 

In the Akka project itself, adding the following to `ByteStringSpec.scala` passes just fine:

```
    "result is the correct class" in {
      val builder = ByteString().genericBuilder[String]
      builder += "foo"
      builder.result.getClass equals classOf[ByteString]
    }
```

Next step is to debug back into the serialization on the app as it is deployed, verify that it is still producing a `Vector`, then weep.

**Comment by briantopping** [comment]
Created akka/akka#19466.

**Comment by luben** [comment]
BTW, it may be lot easier to create specialized serialized for ByteString than fixing it. I will give it a try

**Comment by luben** [comment]
Can you give a try of https://github.com/luben/akka-kryo-serialization/commit/fc92ef80fd70f70fede4709205e44ff1b44849e0

**Comment by briantopping** [comment]
on it

**Comment by luben** [comment]
Note that the test case that compares the classes will still fail because there are multiple classes implementing ByteString so in this case you will get "akka.util.ByteString$ByteString1" instead of "akka.util.ByteString$ByteString1C"

**Comment by luben** [comment]
You can also test https://github.com/luben/akka-kryo-serialization/commit/d1c444e993d722c7f0e71c0d385355cdfeda01c5 - it optimized the deserialization: we don't need a builder because we can construct it from the Array[Byte] we get from Kryo

**Comment by briantopping** [comment]
I had to get my hong kong girl off video, then realized I was on the wrong repo, then had to merge the classloader fix.

Good news: It works!!

**Comment by briantopping** [comment]
Are you on gitter?

**Comment by briantopping** [comment]
so I was using `d1c444e`

**Comment by luben** [comment]
I have sent also a pull request for the new serializer: https://github.com/romix/akka-kryo-serialization/pull/70
It also includes the tests that I have copied from you with small cleanup of the config. I can remove it and leave your PR to be merged for the tests.

**Pull request closed without merging**
