### PR TITLE
Fix for #65, got lucky that this was a one-line change. Whew!

### PR DESCRIPTION
**Pull request by briantopping**

### CODE REVIEW

**Comment by romix** [comment]
Is this fix always correct in all possible-scenarios, i.e. in all OSGI and non-OSGI scenarios? If not, may be it should be an opt-in solution which can be enabled via an option in a configuration file?

**Comment by briantopping** [comment]
I thought about that too. In non-OSGi environments, there should be only one classloader, so the set will be superfluous. 

Without having a copy of the `BundleContext`, I don't know of a way to tell if one is running under OSGi or not. For instance, the existence of the headers in the `MANIFEST.MF` only means a JAR can be run as a bundle, not that it *is running as* a bundle. 

If we went the configuration file route, what if it was opt-out and then remove the setting if nobody used it a few revisions from now? This would reduce long term complexity. Just a thought.

**Comment by briantopping** [comment]
I see that `KryoSerialization` is using `system.dynamicAccess.getClassFor`, which is going to use the `system.dynamicAccess.classLoader`. So it seems like a misfeature that the classloader Kryo itself is using would be different than the one `system.dynamicAccess.getClassFor` is using, no?

**Comment by briantopping** [comment]
Any reason we can't get this pushed? With #67 fixed, it would be nice to use mainline sources at the next release! :)

**Comment by briantopping** [comment]
Thanks so much!

**Pull request merged**
