### PR TITLE
Make the "default" idstrategy register the mappings

### PR DESCRIPTION
**Pull request by luben**
In this way we can incrementally map the classes and fall-back to
the default strategy that is safer than the incrmental.

### CODE REVIEW

**Comment by luben** [comment]
I will force push a correction for the documentation in a moment

**Comment by luben** [comment]
This change was discussed in #83

**Comment by guidomedina** [comment]
@luben stupid question; what's the difference between mapping and classes? Maybe if you assume a high ID number then you might not need a numbered mapping but respect the classes order starting at such ID?

Say 1000.

**Comment by guidomedina** [comment]
@luben and another question, with explicit mapping, would use-manifest make it smaller or bigger?

**Comment by luben** [comment]
with explicit mapping the size will be smaller. The difference between mapping and classes is that you assign the ids manually in the mapping but they are assigned incrementally in for the 'classes'. For the mappings we do ```kryo.register(class, id)``` and for classes just ```kryo.register(class)```

**Comment by guidomedina** [comment]
@luben good, that means you can completely ignore the `mappings` section and use `idstrategy = default` with classes only and that should give you the smallest/friendliest config you can get?

**Comment by romix** [comment]
I'm not sure it is a good idea to change the semantics of `default` in a backwards-incompatible way. Some clients of this library may rely on the old semantics. May be it is better to introduce a new mode for this?

**Comment by luben** [comment]
@guidomedina , actually tested it, with explicit mapping the serialized size is 1 byte larger than explicit mappings and use-manifests=true. But it fails the LongMap test.

@romix ,  OK, agree. Do you have suggestions for the name?

**Comment by guidomedina** [comment]
@luben what test is that? it shouldn't fail, if it fail is because you are trying to read top object and class (not the nested objects but parent)

**Comment by guidomedina** [comment]
@romix what about `idstrategy = automatic`

**Comment by luben** [comment]
@romix, sounds good.

**Comment by romix** [comment]
@luben `automatic` is OK with me. It just needs to be properly documented.

**Comment by guidomedina** [comment]
@luben @romix

What about `idstrategy = automatic`
What if you make `default` the `automatic` as nobody explicitly set classes and mapping with default? it won't break any old behavior but add it.

**Comment by guidomedina** [comment]
@luben @romix I don't see how default with extra mappings and classes functionality would at broken people config, as by default people don't add these two lists.

**Comment by luben** [comment]
@guidomedina 

Regarding the failing test: its in the AkkaKryoCompressionTests.scala, the one that excercises immutable.LongMap.

Regarding the default: I agree with romix, lets leave it as-is and create new name for the new behaviour - you don't know that nobody has not added mappings and classes in their configs and still using "defautl" idstrategy.

@romix  force-pushed an update that uses "automatic" (or any other name infact) for the new id-strategy behaviour.

**Comment by guidomedina** [comment]
@luben yeah, I understand what you mean now with some users leaving behind `mappings` and/or `classes`

**Comment by luben** [comment]
@romix force-pushed a rebased version

**Comment by luben** [comment]
Thanks,

I will put extensive tests on this version. I think it may be a goot point for a new release.

Regrds

**Comment by luben** [comment]
It is 1 week in production and bahaving as expected using the new "automatic" idstrategy. I would say to wrap a new minor release.

**Comment by guidomedina** [comment]
@luben @romix Akka 2.4.3 released, it would be nice to release a version if everything is ok.

**Comment by romix** [comment]
@guidomedina Do we need to update any versions in the config to make use of Akka 2.4.3?

**Comment by luben** [comment]
I don't think we have to change it - it's backward compatible release

**Comment by guidomedina** [comment]
Yeah, it is backward compatible, only need to update version from 2.4.2 to 2.4.3 and the release version for akka-kryo

**Comment by guidomedina** [comment]
@romix @luben my previous answer was a bit confusing sorry, what I meant is, no you don't need to update any version because of backward compatibility, but; if you are going to change that file to change the version may as well update to latest akka version while at it.

**Comment by romix** [comment]
I've released the 0.4.1
It is available on the Maven Central already.

**Comment by guidomedina** [comment]
@luben @romix thanks guys, awesome release ;-)

**Comment by romix** [comment]
@guidomedina @luben Thank you for your contributions, guys!

**Pull request merged**
