### PR TITLE
Added AES, ZipAES and LZ4AES serializers, which does aes encryption, deflate compression + aes encryption and lz4 compression + aes encryption respectively.

### PR DESCRIPTION
**Pull request by sunnylbk**
- AES encryption is enabled by setting 'akka.actor.kryo.encryption = aes' and key used for encryption as 'akka.actor.kryo.aeskey = j68KkRjq21ykRGAQ'. By default encryption is set to 'off' and key as 'ThisIsASecretKey'
- For Zip + AES serialiser, data is first compressed and encrypted. Settings are: 'akka.actor.kryo.encryption = aes', 'akka.actor.kryo.aeskey = j68KkRjq21ykRGAQ' and ''akka.actor.kryo.compression = deflate'
- For lz4 + AES, settings are: 'akka.actor.kryo.encryption = aes', 'akka.actor.kryo.aeskey = j68KkRjq21ykRGAQ' and ''akka.actor.kryo.compression = lz4'

### CODE REVIEW

**Comment by luben** [comment]
Some comments:

1. I think that extending KryoCrypto trait was the better alternative than using reflection.

2. Regarding composition. This is how I see it:
- implement AESCrypto class that does only encryption and NoCrypto class that does nothing (like NoKryoCompressor)
- Then you instantiate the proper compressor and crypto classes from the config (use NoCrypto if it is not configured)
- than in fromBinary and toBinary compose the 2 features like:
toBinary:
val bin = crypto.encrypt(compressor.compress(bin))
fromBinary:
val obj = ser.fromBinary(compressor.decompress(crypt.decrypt(bytes)), clazz)

This way it will be  easier to add more crypto and compression methods by just adding crypto/compressor classes

Romix, did I get your idea right?

**Comment by luben** [comment]
Additional comment, may be rename the current AES class something along the lines of AESCBC... There is a value of adding also AES/GCM because it adds also authentication on top of encryption using the same infrastructure

**Comment by sunnylbk** [comment]
@luben 
1. I started out with KryoCrypto trait, but I have seen in other parts of the code, reflection was used to load a class and method using the name. I changed to this to maintain uniformity.
I feel trait approach would be more safe and less error-prone. If that approach is ok, I will change to that

2. Ok, so this means we create a new serialiser for encryption and implement fromBinary and toBinary methods.

3. For AES encryption, we can pass algorithm name as parameter - for CBC it would be 'AES/CBC/PKCS5Padding' and for GCM, it would be 'AES/GCM/NoPadding', We could read the also name from config.

**Comment by luben** [comment]
I think deriving crypto and compression modules from the same interface is a good idea. I think making a generic/composable at runtime pipeline is overengineering. We may want it some day but let's start simple.

If we have to compose it we could use something as:
val pipeline: List[Transformation] = ...
val fromBinary = pipeline.reduceLeft((a,b) => a.fromBinary _ andThen b.fromBinary _)
val toBinary     = pipeline.reduceLeft((a,b) => a.toBinary _      compose b.toBinary _) 

This way you don't need to keep track what is the next step and also don't need to iterate externaly

**Comment by luben** [comment]
@sunnylbk having a way to pass that encryption triplet (hash/mode/padding) will be great option

**Comment by romix** [comment]
@luben I agree that building pipelines at runtime (i.e. by means of an API) is overengineering. But creating a pipeline from a static description in a config file is not that complicated. 

The issue that I don't like in our current implementation is the fact that encryption assumes that it runs after compression. I.e. it implicitly assumes something about our transformation pipeline. To avoid it, I'd like to have a logic in our main class to apply all the required transformations in the right order, e.g. like you sketched above. I think it will make things more robust and more extendable in the future.

**Comment by sunnylbk** [comment]
@romix 
I agree, instead of having separate serializers for compression/encryption, we could derive from same serializer. It boils to some transformation on byte arrays. So, we could override something like fromBinary and toBinary.
And yes, crypto serializer as of now is hardcoded to do compression and then encryption. We could construct the transformation from config.

@luben 
Yes, such a pipeline can be constructed. We could have a new setting in config file, like
```transformer = deflate, aes-cbc```
With this our pipeline becomes, ```List[KryoCompressor, CryptoCompressor]```

Operations as you mentioned earlier, could be done

If someone wants it differently, like 
```transfomer = aes-cbc, deflate```
pipeline then would be, ```List[CryptoCompressor, KryoCompressor]

**Comment by luben** [comment]
@romix  I think that compression before encryption is the right ordering - if you first encrypt you loose compression opportunities because each encrypted block (in CBC and GCM modes)  depends on the result of previous block that breaks regularity and repeating patterns.

@sunnylbk I think composing the transformations is cleaner than inheritance based, at least we will loose some type information:

serializer toBinary: AnyRef=>Array[Byte]
tranform toBinary: Array[Byte]=>Array[Byte]

but it will work either way.

**Comment by romix** [comment]
@luben 

> I think that compression before encryption is the right ordering [snip]

Yes, for this specific kind of transformations (i.e. compression and encryption) it makes more sense.  But I try to think about it in a more general way. What if we add more kinds of transformations later? What if some of them can be executed in any order? Etc... From this perspective, it is better if transformations are not aware what is executed before them or after them. 

Regarding your remark about transform vs serializer: Yes, I'd probably agree that a transform trait feels more natural for transformations, because it more explicitly says that it operates on arrays of bytes. More over, we can always automatically wrap it into a Kryo serializer, should we want it.

**Comment by luben** [comment]
@romix agree on all points

**Comment by romix** [comment]
@sunnylbk Since we all in agreement now, are you going to implement this? I.e. those suggested re-factorings?

**Comment by sunnylbk** [comment]
@romix Yes, I will be implementing the suggested changes.

**Comment by sunnylbk** [comment]
@romix @luben 
I have made changes which I think conforms with what we discussed. I have laid down the idea. I need to do a bit more refactoring.
Let me know your views.

**Comment by sunnylbk** [comment]
I still need to make encryption configurable based on algorithm name

**Comment by romix** [comment]
I had a quick look. Yes, it goes very much in the right direction. I like it!

One minor thing which I'm a bit concerned about is configuration. 

-  I think each kind of transformer (compression, encryption) or even each specific transformer (e.g. aes or lz4 or deflate)  should be configurable. We should allow a subsection in the config for it, e.g. something like
```
kryo.compression.lz4 {
  ...
}
kryo.compression.deflate {
}
kryo.encryption {
   ...
   aes {
   }

   another-algo {
     ...
   }
}
```

We should also somehow predefine the names (e.g. encryption, compression) or we may allow just anything. I'm not sure about it.

- Currently all of our transformers are invoked after serialization/before deserialization, because they work on byte arrays. But in the (distant) future I could imagine transformers being applied also before serialization/after deserialization. Those ones would work on objects, obviously. They could e.g. transform object graph into a different internal representation, which is easier to serialize.... We don't need to think about it yet. But we could at least foresee it and use a proper naming in the config file.
I'd suggest using `post-serialization-transformations` instead of `transformers`.  Later on we may allow for `pre-serialization-transformations`. In the source code, you may also use a similar name for a variable representing the transformation pipeline.

What do you think?

**Comment by sunnylbk** [comment]
Yes, I was actually thinking about this. Having configuration for each transformation provides super flexibility.Pre and post serialization settings also add to that.
So there should be some kind of lookup, wherein, we get the transformers one by one, look for settings and then apply the transformation.

**Comment by romix** [comment]
Yes.

**Comment by luben** [comment]
Yes, re-added them, looks like I forgot to send them

**Comment by sunnylbk** [comment]
@romix @luben 
Updated with new changes

**Comment by romix** [comment]
@sunnylbk Thanks! I looked at it and it looks much better. We are almost done!

Could you provide a few more examples of the configuration file syntax here? I'm not quite sure about the syntax for more complex cases, based on your examples in the patch. I'd just like to see how it would look like.

And, BTW, the README and or default config should be extended to mention those new config options, I guess.

**Comment by sunnylbk** [comment]
@romix 
I am updating README to reflect new changes.
I have another feature in mind, I would like to know your views about it. Now, we have a single aes-key for encryption/decryption. In many instances, the key depends on the context, like each user may have their own key. In such cases, key has to be dynamically passed to serializer.
Thought I have is, we could use something like a key-store to dynamically retrieve the key. I am not sure how seamlessly it could be integrated with this.

Your thoughts?

**Comment by sunnylbk** [comment]
ok...I just realized, we are giving an option to provide a class for key-provider. Such a class could contain any implementation of key-provider - keystore, database calls, url calls, calling from a text file, anything.
We are good.

**Comment by romix** [comment]
Yes, the idea with a class for key-provider is good. This class can be used for all further configs. We also use a similar approach for other things as well, e.g. when a Kryo instance needs to be configured in a very special way, which cannot be expressed in the config file.

**Comment by sunnylbk** [comment]
@romix 
Some config examples:

1.
kryo {
	...
	pre-serialization-transformations = "deflate,aes"
	encryption {
		aes {
			mode = "AES/CBC/PKCS5Padding"
			key = j68KkRjq21ykRGAQ
			}
		}
	...
}

2.
kryo {
	...
	pre-serialization-transformations = "deflate,aes"
	encryption {
		aes {
			mode = "AES/CBC/PKCS5Padding"
			custom-key-class = "com.romix.akka.serialization.kryo.KryoCryptoTestKey"
			}
		}
	...
}

**Comment by romix** [comment]
Yes, I understand that the syntax would look like this. My question was more general. If we have pipe-lines in `pre-serialization-transformations`, do we need to define all possible names that can be used there in advance? Do we need to define which of them belong to which categories, e.g. aes is a sub-element of encryption, deflate is an element of compression. Do we want to provide settings per such name only, e.g. for `aes`, or also for a whole catagery, e.g. for encryption or compression in general.

Can we come up with something, where people could add their own serializers and transformers, without changing the library? E.g. the config would mention a class (or JAR) where additional serializers/transformers can be found and the library would use it to register those extensions. The extensions may in turns register their own `names` that can be used in the pipelines, etc. They can also parse their own parts of the configuration file....  

But these are just minor remarks. Just some related ideas. It is not directly related to this issue and is probably beyond its scope.

**Comment by luben** [comment]
@sunnylbk as far as I understand compression and encryption happens after serialization so they should be in post-serialization-transformations, not pre-serialization-transformations. I see that you are using the "pre-serialization..." config key in the tests and the comments here.

@romix What about shipping a version with only "post-serialization-transformations" (crypto,compression) without "pre-serialization-transformations" and adding it later?

**Comment by romix** [comment]
@luben Yes, we could do it. And good catch regarding "pre" and "post"! I missed this ;-)

**Comment by sunnylbk** [comment]
@romix 
Sorry, was travelling during weekend. Yes, I think all the transformations should be defined in config file, because we need to have implementation for each of those inside code.
Or else, as you suggested, a user should be able to add their own serializer and provide an implementation of their own. Now I see the config becoming more complex ;)

We could allow a user to add their own serializer with their own implementation, and provide their own transformations, like:
```
ser1-class = com.blah.Uppercaser
ser2-class = com.blah.Compressor

post-ser-transformations = ser1, ser2

```
I don't see maintaining categories as an extensible way of adding new serializers. Because a user has to know what categories are there and should he place his own serializer in one of the existing categories or create a new one. We can have settings for each of the serializers.

**Comment by sunnylbk** [comment]
@luben 
Yes, it should be post-ser-transformations. Will change that.

**Comment by luben** [comment]
@sunnylbk I agree that maintaining categories is not a scalable solution

**Comment by romix** [comment]
@sunnylbk @luben Yes, maintaining categories will not scale. Let's forget about it ;-)

**Comment by luben** [comment]
what about some configuration like:
...
transformations {
  post-serialization-transformations = lz4, aes
  lza {
    class = "....LZ4Compress"
  }
  aes {
    class = "....AesEncryption"
    key = "secret"
    ...
  }
}

**Comment by romix** [comment]
May be. It would mean that users need to know the name of those classes implementing whatever transformation. It is not bad as such. We just need to document the set of pre-defined transformations that are shipped as a part of the library. Eventually, we may even ship them as add-on libraries if we support the configuration approach like this.

**Comment by sunnylbk** [comment]
@romix @luben 
Kryo 3.0 released!
https://github.com/EsotericSoftware/kryo#new-in-release-300

**Comment by romix** [comment]
@sunnylbk Yes, indeed ;-) Could you try if everything still works if you update the dependency to 3.0? 
If this is the case, I suggest submitting a tiny separate PR for it. No need to put into this encryption related PR.

**Comment by sunnylbk** [comment]
Kryo 3.0 passes all the tests.

@romix 
I would like to add some persistence related tests to see kryo-serializer works well with recovering snapshots.

**Comment by romix** [comment]
Nice!

Yes, adding persistence tests is a good idea. But keep in mind that Kryo does not guarantee a binary compatibility of serialized data between different Kryo versions.

**Comment by sunnylbk** [comment]
@romix 
Added persistence snapshot tests.

Also, after encryption, it's safer to encode data to base64 format. Base64 utils, by default in java, are provided by sun(sun.misc._), which are no longer maintained.
In Java8, base64 utils are included inherently (http://docs.oracle.com/javase/8/docs/api/java/util/Base64.html). So, for older versions of java we need to use some other library like apache commons (http://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html) to do the job.

**Comment by luben** [comment]
@sunnylbk Why encode in Base64? It is binary data after all. If we need Base64 encoding/decoding it may be an new transformation like aes,deflate and lz4

**Comment by sunnylbk** [comment]
@luben 
ah...yes!

@romix @luben 
I think I am done with the additions. If everything is fine, I will go ahead and update the readme file.

**Comment by romix** [comment]
Yes, very good job! I have no further comments and proposals on my side. Please go ahead and update the readme.

**Comment by luben** [comment]
Look good to me also. Compared the performance with master and there are no regressions.

Before releasing, things that may to be updated in the build:

Kryo-3.0.0 - improves serialization speed
LZ4-1.3.0 - some improvements
akka - 2.3.8
scala-2.11.5

I have tested it the above dependencies and everything works.

**Comment by romix** [comment]
@luben Thanks for comparing the performance with master! Could you submit a small PR for dependencies versions updates once we merged this PR? Then we are ready for a release.

BTW, could you test with a trunk version of Kryo? The default instantiation strategy was changed - it does not allow for classes without no-arg constructors anymore. It would be useful to see if it breaks anything on our side and if so, include some workaround for it, e.g. set the default instantiation strategy by hand in our code without relying on Kryo to do so.

**Comment by luben** [comment]
@romix Will send a PR with updated dependencies. I also saw that they have broken the no-args constructors in later commits. Will try to compile and see what is the result.

**Comment by luben** [comment]
@romix I tested it with kryo/master - all the tests pass.

**Comment by romix** [comment]
@luben Nice! Thanks! Then we are almost done for release.

**Comment by luben** [comment]
@romix I sent another PR with the updated dependencies and the bumped the version

**Comment by romix** [comment]
@luben Thanks! Do I need to wait for this PR to be finished or can I merge your already now?

**Comment by luben** [comment]
I don't think they conflict so they could be applied in any order. Mine is also based on master

**Comment by romix** [comment]
@sunnylbk Looks like after I merged @luben's PR, there is a small conflict (in the sbt config, I guess). Could you look into this? 

Also, what about the README update?

Once this two things are done, I can merge and we are ready for a release.

**Comment by sunnylbk** [comment]
@romix 
I have merged the latest changes, with local changes. Conflicts should be resolved now.
I have already updated README file.

**Comment by analytically** [comment]
akka.actor.kryo.aeskey=ThisIsASecretKey-${RANDOM}

**Comment by romix** [comment]
@sunnylbk Thanks! Then let's merge it! :-)

**Comment by romix** [comment]
@sunnylbk @luben Now that it is released, does this new release work for you as expected?

**Comment by sunnylbk** [comment]
@romix I am using this to persist encrypted serialized classes into a journal and replay them on crash. Code is not yet in production, but tests pass consistently. So, working for me! :)

**Comment by luben** [comment]
@romix it works for me as expected

**Comment by luben** [comment]
@sunnylbk I have pushed some fixes for the AES transperent encryption:

- use randon IV for each request (it has to be non-repeating)
- serialized the IV in the bytestream so that it can be used in the decrption phase.

It will break the persisted encrypted state but I am not sure that it was working properly before (you need the IV in order to decrypt the message). Any comments and concerns are welcome.

**Pull request merged**
