### PR TITLE
Build for Scala-2.12

### PR DESCRIPTION
**Pull request by luben**
+ Fixes a few deprecation warnings and a test.
+ Use not the highest optimization level for scala-2.12 (-opt:l:classpath) in order to make the produced jar work with different minor versions  of the dependencies.
+ Addresses #105

### CODE REVIEW

**Comment by romix** [comment]
@luben Thanks for the PR! Looks good. Do we want to release a new minor version for it, e.g. 0.5.1?  If so, we'd need to update the README to provide proper version numbers.

**Comment by luben** [comment]
I think it's cleaner to push a new version. I will update the versions in the README

**Comment by romix** [comment]
Thanks!

**Comment by romix** [comment]
@luben I performed the "sbt release", but I think it has not releases the cross-compiled version. 

I'm trying to follow the steps described in https://github.com/sbt/sbt-release, but without success yet. Just adding "releaseCrossBuild := false" does not work. sbt complains about it. May be something needs to be imported? Or may be our Build.scala needs to be rewritten as build.sbt? Do you have any ideas or experience with cross-builds?

**Comment by luben** [comment]
I need to do "+compile" and "+test" in order to cross-build and test. May be you need to do "+release" to do cross release.

**Comment by romix** [comment]
@luben I tried "release cross", but it didn't work for me. As for  "releaseCrossBuild := true" (this is what I meant in the previous message, but mentioned "false" for some reason) - I don't quite understand where to put. I tried to add it as one of the settings in our Build.scala file, but then sbt would complain about errors in this file.

**Comment by luben** [comment]
Reverted the sbt to the previous version: 0.13.9. I have checked the 0.3.3 that was the last that we have been cross-building for 2.10 and 2.11 (no releaseCrossBuild setting) it uses sbt-0.13.7, you can try with it also.

**Comment by romix** [comment]
I just pushed 0.5.2 with some changes to build project settings. I've even seen that it has build both versions. But I think it pushed only one of them to Sonatype ;-( I guess I miss something, but I don't know what it is. And it is pretty annoying that I cannot do a dry-run to figure out the right set of options. Every attempt results in a new release :-(

FYI, I'm using "sbt release" for pushing a release. Last time I tried to start sbt without arguments and then gave it a command "release cross".

**Comment by romix** [comment]
Because of the issues with cross-builds, we seem to have issues with publishing on Maven Central as users report. If anyone knows how to properly configure cross-builds and how to publish them - any help is appreciated! In the meantime I created the following issue that should address it: #107

**Comment by magro** [comment]
I've never used the sbt release plugin, but AFAICS the `releaseCrossBuild` setting is missing.

**Pull request merged**
